### ISSUE TITLE
[Feature request] UPower integration?

### ISSUE THREAD

**Issue by parkerlreed** [TheWeirdDev/Bluetooth_Headset_Battery_Level#38] opened 2020-08-08 19:01 UTC
Would be nice to have this as a daemon that could report battery level to UPower (so that it could in turn be picked up be the DE and shown in the local battery reporting applet)

**Comment by TheWeirdDev** [comment] 2020-08-09 08:19
That's a good idea but i think it would be a whole new project. I'm not sure exactly how it's done but we probably need to write a kernel module for it.
Another user was trying to achieve the same functionality with a gnome-shell extension. That's a lot easier to do.

**Comment by GiovanniSM20** [comment] 2020-11-17 17:10
@parkerlreed are you referring to "plugins" in the information bar ? Like bluetooth and others stuffs present on bar ?

**Comment by parkerlreed** [comment] 2020-11-17 17:20
Yeah like how mouse battery and stuff shows up to the system.

```
[parker@stealth ~]$ upower -e
/org/freedesktop/UPower/devices/line_power_AC0
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/mouse_hidpp_battery_1
/org/freedesktop/UPower/devices/DisplayDevice
[parker@stealth ~]$ upower -i /org/freedesktop/UPower/devices/mouse_hidpp_battery_1
  native-path:          hidpp_battery_1
  model:                MX Ergo Multi-Device Trackball
  serial:               406f-41-f4-e8-0e
  power supply:         no
  updated:              Tue 17 Nov 2020 12:19:40 PM EST (26 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    battery-level:       full
    percentage:          100% (should be ignored)
    icon-name:          'battery-full-charged-symbolic'
```

**Comment by GiovanniSM20** [comment] 2020-11-17 20:27
maybe i can do it but not exactly now because i'm busy until thursday at work and friday here in brazil is a holiday so maybe i can sit friday, saturday and sunday to do (or just on one of these days, it doesn't seem complicated)

**Comment by GiovanniSM20** [comment] 2021-02-04 00:52
found this and it can be interesting: [argos](https://github.com/p-e-w/argos)

**Comment by parkerlreed** [comment] 2021-02-04 01:21
Yeah that's always an option. KDE/Plasma is about as simple to create a custom widget. The UPower idea was to make it integrate into the normal battery reporting mechanisms of whatever desktop environment you use.

**Comment by MichalW** [comment] 2021-02-04 08:01
@GiovanniSM20 

I have created a gnome extension that shows an indicator with a battery level and uses this package as a submodule.
I am still waiting for approvals on the extensions.gnome.org website.
In the meantime, you can install manually:
https://github.com/MichalW/gnome-bluetooth-battery-indicator

**Comment by TheWeirdDev** [comment] 2021-02-04 08:47
@MichalW
Cool! Send the link after approval, so I can add it to the readme file.

**Comment by GiovanniSM20** [comment] 2021-02-04 11:23
So I think we can close this issue @TheWeirdDev

**Comment by TheWeirdDev** [comment] 2021-02-04 11:57
So I guess there will be no UPower integration for this project. I'll close this issue but if anyone wants to work on UPower, send me a message.

**Closed by TheWeirdDev** 2021-02-04 11:57 UTC

**Comment by MichalW** [comment] 2021-02-06 20:31
@TheWeirdDev @GiovanniSM20 @parkerlreed 
https://extensions.gnome.org/extension/3991/bluetooth-battery/

**Comment by TheWeirdDev** [comment] 2021-02-07 06:21
> @TheWeirdDev @GiovanniSM20 @parkerlreed
> https://extensions.gnome.org/extension/3991/bluetooth-battery/

Thanks for your work.
I tried it with both my headphones and it doesn't show anything.

![image](https://user-images.githubusercontent.com/6321734/107138410-6db3af00-6929-11eb-87d4-f2ba05e60b36.png)

I checked the logs and it seems like everything is ok. Do you have any idea why it won't show the battery level?

![image](https://user-images.githubusercontent.com/6321734/107138462-caaf6500-6929-11eb-98fb-6ae8cb9b53fe.png)

**Comment by MichalW** [comment] 2021-02-07 08:48
Please try to change something in settings (eg. interval) and after that click on the refresh button.
Does the icon sometimes jump right/left?
I wonder if the styles aren't the problem. Maybe the color of the text or the size makes it invisible.
Do you have any custom gnome theme?

**Comment by TheWeirdDev** [comment] 2021-02-07 13:07
@MichalW 
I changed settings options and still got no label.

I am using a custom theme, but I don't think that's the issue because I gave the label a custom text and it's showing it fine.
![image](https://user-images.githubusercontent.com/6321734/107147296-796f9780-6962-11eb-8b18-64c7e7ae86ed.png)

We need more testers.

**Comment by TheWeirdDev** [comment] 2021-02-07 13:15
I have 7 Bluetooth devices in the list and the last one is my headset. I printed the index number and it shows 6.
There is only one indicator enabled, so the index should be 0. After enabling all of my devices in the settings, I finally get the battery level.
![image](https://user-images.githubusercontent.com/6321734/107147502-b8521d00-6963-11eb-86ae-3d5d25f0cfa4.png)

So the 'index' variable is definitely miscalculated.

**Comment by MichalW** [comment] 2021-02-07 13:42
Thank you very much for your help,
I was able to reproduce the problem and will fix it asap.

**Comment by ajithkumar-natarajan** [comment] 2021-02-25 15:57
@MichalW Thanks for the extension. I use a Beoplay H4 headphone and I face the same issue as @TheWeirdDev. I am able to see just the headphone icon in the applet, without any indication of the battery percentage.

**Comment by MichalW** [comment] 2021-02-27 11:24
@ajithkumar-natarajan Did you try to run the `bluetooth_battery.py` script? Is it showing properly the percentage?

**Comment by ajithkumar-natarajan** [comment] 2021-02-27 21:31
@MichalW When I run it, it is weirdly saying that the device is offline. `<MAC_address> is offline [Errno 111] Connection refused`

**Comment by develop-algoritma** [comment] 2023-01-08 15:39
Hello, thanks for work work.

I have a little problem and a big one.

The little is that my Keyboard have two icons, the keyboard and the headphones.

![image](https://user-images.githubusercontent.com/31618014/211205449-1bf34eb2-cf0b-446a-90ed-5937bd6a892e.png)

The big problem is that my mouse (MX Master 3s) is not detected by the extension

![image](https://user-images.githubusercontent.com/31618014/211205368-f9c454fd-60e6-457d-88dd-e0b037b01e8c.png)

Thank you!
