### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by meetdilip** [TheWeirdDev/Bluetooth_Headset_Battery_Level#88] opened 2023-01-05 08:54 UTC
Hi, 

Got this error in Ubuntu 22.04

```
python3 bluetooth_battery.py xx:xx:xx:xx:xx:xx
Traceback (most recent call last):
  File "/home/myname/Downloads/Bluetooth_Headset_Battery_Level-master/bluetooth_battery.py", line 166, in <module>
    main()
  File "/home/myname/Downloads/Bluetooth_Headset_Battery_Level-master/bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/home/myname/Downloads/Bluetooth_Headset_Battery_Level-master/bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/home/myname/Downloads/Bluetooth_Headset_Battery_Level-master/bluetooth_battery.py", line 105, in _perform_query
    sock.send(b"+BRSF: 1024")
  File "/home/myname/Downloads/Bluetooth_Headset_Battery_Level-master/bluetooth_battery.py", line 66, in send
    return super().send(b"\r\n" + data + b"\r\n")
  File "<string>", line 3, in send
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

I tried ./bluetooth_battery.py xx:xx:xx:xx:xx:xx

and 

bluetooth_battery.py $(bluetoothctl info | awk '/^Device/ {print $2}')

commands too, without success. Any help would be great.

**Comment by TheWeirdDev** [comment] 2023-01-05 15:42
Duplicate of #78 , follow the instructions in that thread.

**Closed by TheWeirdDev** 2023-01-05 15:42 UTC

**Comment by meetdilip** [comment] 2023-01-06 03:28
Thanks. This command solved my issue 

`pip3 install git+https://github.com/pybluez/pybluez@master`

Can see the battery percentage through the Gnome extension
