### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by dee0xeed** [TheWeirdDev/Bluetooth_Headset_Battery_Level#95] opened 2024-02-23 17:58 UTC
At some moment (probably after some Mint dist upgrades) the script stopped working for me, I see this:

```
$ ./bluetooth_battery.py D3:D2:CA:93:93:CC
Traceback (most recent call last):
  File "./bluetooth_battery.py", line 283, in <module>
    main()
  File "./bluetooth_battery.py", line 272, in main
    result = query.query()
  File "./bluetooth_battery.py", line 131, in query
    result = self._perform_query_rfcomm()
  File "./bluetooth_battery.py", line 151, in _perform_query_rfcomm
    sock.send(b"+BRSF: 1024")
  File "./bluetooth_battery.py", line 70, in send
    return super().send(b"\r\n" + data + b"\r\n")
  File "<string>", line 3, in send
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

Python version is

`Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux`

**Comment by TheWeirdDev** [comment] 2024-02-24 06:05
Duplicate of https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/78 , follow the instructions in that thread.

**Closed by TheWeirdDev** 2024-02-24 06:05 UTC

**Comment by dee0xeed** [comment] 2024-02-24 11:08
Oops, sorry for duplicate, I did not look into closed issues before posting, my bad.
Thanks for the link.
