### ISSUE TITLE
Systemerror using Python 3.10

### ISSUE THREAD

**Issue by SvenZHB** [TheWeirdDev/Bluetooth_Headset_Battery_Level#73] opened 2021-12-30 07:43 UTC
Using Python 3.10 on Manjaro (Arch) throws an error using the software.

`Traceback (most recent call last):
  File "/usr/local/bin/bluetooth_battery", line 33, in <module>
    sys.exit(load_entry_point('bluetooth-battery==1.3.2', 'console_scripts', 'bluetooth_battery')())
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 105, in _perform_query
    sock.send(b"+BRSF: 1024")
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 66, in send
    return super().send(b"\r\n" + data + b"\r\n")
  File "<string>", line 3, in send
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
`

**Comment by TheWeirdDev** [comment] 2021-12-30 08:11
Duplicate of #71 (It's a pybluez bug and you have to wait for them to fix it).

**Closed by TheWeirdDev** 2021-12-30 08:11 UTC
